#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "Error: File '$PYFILE' not found."
    exit 1
fi

# Compile the Python script
python3 -m py_compile "$PYFILE"

# Get the base filename without the extension
base_filename=$(basename "$PYFILE" .py)

# Rename the compiled .pyc file to use the base filename
mv "__pycache__/$base_filename.cpython-*.pyc" "${base_filename}c"

echo "Compiling $PYFILE ..."

